version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    # healthcheck:
    # test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
    # interval: 5s
    # timeout: 3s
    # retries: 10
    # command: ["postgres", "-c", "shared_preload_libraries=pgvector"]

  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app
      - ./data/split_images:/data/split_images:ro
    ports:
      - "8000:8000"
    depends_on:
      - db

  ui:
    build: ./ui
    command: sh -c "pnpm dev -H 0.0.0.0 -p 3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db_data: